name: Unit Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true

      - name: Install dependencies
        run: |
          go mod download
          # Pin specific version of cel-go as required by k8s components
          go get github.com/google/cel-go@v0.22.0

      - name: Run tests
        run: go test ./... -v

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: coverage.out
          if-no-files-found: ignore
